name: tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize] }
  push: { branches: [main] }

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        swift-image:
          - name: swiftlang/swift:nightly-6.2-noble
            continue-on-error: false
          - name: swiftlang/swift:nightly-main-noble
            # Disbale failures on nightlies for now
            continue-on-error: true
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ubuntu-latest

    container: ${{ matrix.swift-image.name }}

    timeout-minutes: 15

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Install zstd for faster caching, and curl for codecov action
        run: |
          apt-get update -y
          apt-get install -y zstd curl

      - name: Restore .build
        if: ${{ runner.debug != '1' }}
        id: "restore-cache"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"

      - name: Build ${{ github.event.repository.name }}
        continue-on-error: ${{ matrix.swift-image.continue-on-error }}
        run: |
          swift build \
            --build-tests \
            --enable-code-coverage \
            --enable-experimental-prebuilts \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Cache .build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        continue-on-error: ${{ matrix.swift-image.continue-on-error }}
        run: |
          swift test \
            --skip "IntegrationTests." \
            --skip-build \
            --enable-code-coverage \
            --enable-experimental-prebuilts \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Submit code coverage
        continue-on-error: ${{ matrix.swift-image.continue-on-error }}
        uses: vapor/swift-codecov-action@v0.3
        with:
          build_parameters: "-c ${{ matrix.config.mode }}"
          codecov_token: "${{ secrets.CODECOV_TOKEN }}"

  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        swift-image:
          - name: swiftlang/swift:nightly-6.2-noble
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ubuntu-latest

    container: ${{ matrix.swift-image.name }}

    timeout-minutes: 15

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Install zstd for faster caching, and curl for codecov action
        run: |
          apt-get update -y
          apt-get install -y zstd curl

      - name: Restore .build
        if: ${{ runner.debug != '1' }}
        id: "restore-cache"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"

      - name: Build ${{ github.event.repository.name }}
        run: |
          swift build \
            --build-tests \
            --enable-experimental-prebuilts \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Cache .build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        run: |
          swift test \
            --filter "IntegrationTests." \
            --skip-build \
            --enable-experimental-prebuilts \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}
